//insert into user (lastname, firstname) values ('Sawitzki', 'Werner');
//select * from user where lastname = 'Sawitzki';
//alter table user add middle_initial text;
//insert into user (lastname, firstname, middle_initial) values ('Sawitzki', 'Werner', 'R.');
//insert into user (lastname, firstname, description) values ('Sawitzki', 'Werner', 'a brother');
//delete from user where lastname='Sawitzki'; //löscht de gesamte Partition
//delete from user where lastname='Sawitzki' and firstname='Werner';
//delete description from user where lastname='Sawitzki' and firstname='Werner';