//drop table if exists person;
//create table person(lastname text, id uuid, firstname text, height smallint, weight float, primary key (lastname, id));
//insert into person (lastname, id, firstname, height, weight) values ('Sawitzki', uuid(), 'Rainer', 173, 101.3);
//insert into person (lastname, id, firstname, height, weight) values ('Sawitzki', uuid(), 'Klaus', 176, 71.3);
//insert into person (lastname, id, firstname, height, weight) values ('Mustermann', uuid(), 'Hanna', 163, 51.3);
//insert into person (lastname, id, firstname, height, weight) values ('Metzger', uuid(), 'Georg', 193, 99.3);
