version: '2'
services:
  cassandra1:
    image: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=javacream_cluster
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=1024M

  cassandra2:
    image: cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME=javacream_cluster
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=1024M

    ports:
      - "9043:9042"
  cassandra3:
    image: cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME=javacream_cluster
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=1024M
    ports:
      - "9044:9042"